export const GET_SAFETY_TIP_REQUEST = "GET_SAFETY_TIP_REQUEST";
export const GET_SAFETY_TIP_SUCCESS = "GET_SAFETY_TIP_SUCCESS";
export const GET_SAFETY_TIP_FAILURE = "GET_SAFETY_TIP_FAILURE";

// Admin actions
export const GET_ALL_SAFETY_TIPS_REQUEST = "GET_ALL_SAFETY_TIPS_REQUEST";
export const GET_ALL_SAFETY_TIPS_SUCCESS = "GET_ALL_SAFETY_TIPS_SUCCESS";
export const GET_ALL_SAFETY_TIPS_FAILURE = "GET_ALL_SAFETY_TIPS_FAILURE";

export const CREATE_SAFETY_TIP_REQUEST = "CREATE_SAFETY_TIP_REQUEST";
export const CREATE_SAFETY_TIP_SUCCESS = "CREATE_SAFETY_TIP_SUCCESS";
export const CREATE_SAFETY_TIP_FAILURE = "CREATE_SAFETY_TIP_FAILURE";

export const UPDATE_SAFETY_TIP_REQUEST = "UPDATE_SAFETY_TIP_REQUEST";
export const UPDATE_SAFETY_TIP_SUCCESS = "UPDATE_SAFETY_TIP_SUCCESS";
export const UPDATE_SAFETY_TIP_FAILURE = "UPDATE_SAFETY_TIP_FAILURE";

export const DELETE_SAFETY_TIP_REQUEST = "DELETE_SAFETY_TIP_REQUEST";
export const DELETE_SAFETY_TIP_SUCCESS = "DELETE_SAFETY_TIP_SUCCESS";
export const DELETE_SAFETY_TIP_FAILURE = "DELETE_SAFETY_TIP_FAILURE";

export const CLEAR_SAFETY_TIP_ERROR = "CLEAR_SAFETY_TIP_ERROR";
