services:
  mysql:
    image: mysql:8.4
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: myapp_db
      # JWT Secret (required!)                                                                                                                                                                
      APPLICATION_SECURITY_JWT_SECRET_KEY: 635D2472BFCDB538749103121A0000117253039B34B43C5E1A26E4F1EF4BCF16                                                                                   
      APPLICATION_SECURITY_JWT_EXPIRATION: 86400000                                                                                                                                           
      APPLICATION_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION: 604800000                                                                                                                            
      # OTP                                                                                                                                                                                   
      TWO_FACTOR_AUTH_OTP_EXPIRATION_MINUTES: 5                                                                                                                                               

    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  backend:
    image: datto04/myapp-backend:1.0
    container_name: spring-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myapp_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-net

  frontend:
    image: datto04/myapp-frontend:1.0
    container_name: react-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"  # Mở port 80 cho web
    networks:
      - app-net

volumes:
  mysql-data:

networks:
  app-net:
    driver: bridge