export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";

export const ADD_USER_MESSAGE = "ADD_USER_MESSAGE";
export const CLEAR_CHAT = "CLEAR_CHAT";
export const SET_CHAT_CONTEXT = "SET_CHAT_CONTEXT";
