export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const MARK_AS_READ = "MARK_AS_READ";
export const MARK_ALL_AS_READ = "MARK_ALL_AS_READ";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";
